language: node_js
node_js:
  - "10"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  # - npm install -g yarn
  - npm install -g codecov

script:
  # - yarn build --base-href https://kaukov.github.io/arcade-game/
  - codecov
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./dist/
  keep_history: true
  on:
    branch: master
